### PR TITLE
Big improvements

### PR DESCRIPTION
**Pull request by CameronSamuels**
### 81e0059
Changed extension description. "FCC Dashboard" was too little, and the FCC isn't that good in the news right now because of #netNeutrality

### 866d9b8
Made searching open in the same tab instead of a new tab.

### a003621
Removed unneeded code to clean it up.

### f0e69b9
- Added instructions for cloning with other applications (GitHub Desktop, cmd, PowerShell)
- It wasn't sensing the last bullet and thought it was an asterisk.
- Fixed grammar and capitalization
- Improved consistency
More

### e31a86e
Removed .DS_Store's and prevented them from being committed via .gitignore. They are an unneeded file and is meant to contain folder properties on a Mac.

### CODE REVIEW

**Comment by CameronSamuels** [comment]
I still have way more code to contribute. So this extension will become way better with knowledge from many people.

**Comment by austen-wade** [comment]
@CameronSamuels 
We're planning to turn this extension into an Electron app soon. It's probably a good idea not to use too much energy on the extension version of it. Just a heads up, if that's something you're interested in. Of course, the Chrome Extension will always be here.

**Comment by CameronSamuels** [comment]
@austen-wade, thanks for the knowledge. Could I manage this version once you all switch to electron? I also have a question: should I remove the content scripts and browser action? I don't see this as a purposeful use.

**Comment by austen-wade** [comment]
@CameronSamuels 
That's very possible. We'll discuss it in our next meeting.

With that in mind, and Abel tells me you have experience with Chrome Extensions, do you think you could perform sort of an audit on what permissions we do and don't need in addition to the content scripts and browser action? This is of course a voluntary task I'm asking of you, but if you want to do that, that would be awesome. Then just send it as an email to Abel.

I think we should reconfigure the extension as a whole. When it was first created, we didn't really have a good of what we did and didn't need yet. I think now we could really quantify some of that. I actually set it to use _all_ of the possible permissions, and that's probably unnecessary. Let me know if you can look into that.

**Comment by CameronSamuels** [comment]
I will look into that.

**Pull request merged**
